name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.4.3)'
        required: true
        type: string

jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64, local]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build plugin for Linux
        run: |
          cd cmd/plugin-sdk
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o libfalco-nginx-plugin-linux-amd64.so
          ls -la libfalco-nginx-plugin-linux-amd64.so
          file libfalco-nginx-plugin-linux-amd64.so
          sha256sum libfalco-nginx-plugin-linux-amd64.so > checksums.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-binaries
          path: |
            cmd/plugin-sdk/libfalco-nginx-plugin-linux-amd64.so
            cmd/plugin-sdk/checksums.txt

  create-release:
    needs: build-linux
    runs-on: [self-hosted, linux, x64, local]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: plugin-binaries
          path: ./artifacts

      - name: Create checksums file
        run: |
          cd artifacts
          sha256sum libfalco-nginx-plugin-linux-amd64.so > checksums.txt
          sha256sum ../rules/nginx_rules.yaml >> checksums.txt
          cat checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            artifacts/libfalco-nginx-plugin-linux-amd64.so
            rules/nginx_rules.yaml
            artifacts/checksums.txt
          body: |
            ## Release ${{ github.event.inputs.version }}
            
            ### What's Changed
            - Fixed Linux binary (previous release had macOS binary by mistake)
            - Built using GitHub Actions self-hosted runner
            
            ### Installation
            ```bash
            # One-liner installation
            curl -sSL https://raw.githubusercontent.com/takaosgb3/falco-plugin-nginx/main/install.sh | sudo bash
            ```
            
            ### Checksums
            See checksums.txt for SHA256 verification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}